sudo: required
group: deprecated-2017Q3
language: scala
services:
- docker
before_install:
  #  Use GPG encryption because it reduces the number of secrets that must be
  #  managed across repositories.  When forking a repository as a core
  #  contributor, contact maintainer to have a newly-encrypted GPG passphrase
  #  communicated.
- for i in ./tools/travis/tls/*/*.pem.gpg; do
    echo "${multiarch_encryption_pwd}" | gpg --passphrase-fd 0 "$i"
  done
- echo "${multiarch_encryption_pwd}" | gpg --passphrase-fd 0 ./tools/travis/docker-local.gradle.gpg
- cp ./tools/travis/docker-local.gradle .
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
- provider: script
  script: "./tools/travis/publish.sh openwhisk ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: Y1ldwIQ6bc3/3Pc0E+qQ6K2M830B9BObYDlsNilPwF/kak3YSfF7SuXuRbJGjTdhH2KOotZD2CwONgP2yvOSPBToC/HpnXYfAGtgblrxQORvgdik88CFWa3Lli1pwlpdzKQNWhBvglzq+IIS98wqzmwqGr8zKA+Iau2ByHdb1j3M9rrIY9V6oU9Gwim1apcRyfI/as3+QfPtt8BUAl2U7+PprxwJigyF/mcZnBJbd7IjrilE2gldZLxKlBiffoKVBinrEg3IQGJPt6k8riw264pBQEpcA0ZBsPUvMaISSxLb+d1ymp3WsiTJUjv+URR/HcdDa7P9jY+ouc8PQz4Yt+Ii38lM2tQU480APfVTyfj6drkjL/+54mYuxm8TzkBWcM2j6/FYT+8HvK/pF35wDJ3El+jGq7BARXg8HVxFsZgynJnhqhWDQb3xX9fK+N4K8+ct+HlsOSa5mP5i5Yo6WRTrWrFpyxVnv9crKePCiYqA2Y8ta8Wnh0sM06nLRtDbfbDjvXPQbaZqSnL4B2Cto08YoT/W/lu8QgJ3EEFlUdDOke4kv9yoXtuE0h7+8dwOvBNMVrBis3G2EYObgR4WmWjk4loYhqT9h3jrH0/5bGLzSKc++qYW0rOZ/RB21cRSe1ILQvSzWkImUoPI8b0i5baGSDq3EjTXYr3pIXSYpQk=
  - secure: DOg+FgllLbyv7nEK3JJZfO/cvXy5K0L6QI/S9EJ/ivm4XBDCw1ayhrSQXvp1tMTPbWBEIv2gomPsHghJ+hVvX3dgwYdoNz9WZaNBB6lOO9U8OQW0LBsO5Eai6grzqOP35OuKtthuyR3dGJHAZo/XjhZM/jL0z6q1kNDzdS7ASwRwHJG0rHPGVlGeolH4nAity4KNJvyAspS1FYaIj9FEC/M7UT6nJVACbr9iMt/83teF/Oo2uoFI6Pa4K3nE2NViVFibToNOM3CV8kArDPDoNJviXxQ07ZM6fNijwehZ80waiPSaxFY8PLSntQNxGyB3DbomSTCcdVvtuHHQVmZgpVdvOJE8wk3R09+nq9U9FuUWLiRYSRbF1eF48YFnssPW1jEeVSenFRADcQ37e4B21ssLvXRHpQHpPVrYBZ8ffDamS7pKtEqocX/3Syc6irxHGCpxEdhvQ0Of5AWHhzB714VCijJJQiH9J4hEKXhMeAZ5SSt4eUavEHJKMhUcJ/aaku5w1+KtiYeOso1fTRbTYkEYb1A0bSNdXlGrYRRT+N683W7+ENiQIT+hTp617L/m5WQLIHfKe3gy5qt46kHFiUL3R3YlBI5OKjnLkDnUiA+0d4SFtJC/TBuPmH1fG4isAuvggTjzCb3kUG3ysin8AW0AKaXW0eqjKa/nsHWDKmc=
  #  The secure entry immediately below is where the GPG passphrase is encrypted by Travis
  - secure: YoAW+ih220qU9o/WG0FfxOheO0wikU318vSBbJxpomF1HELOCnCEqH9/oM1b16BPLpmYPwWFdNvdlk5ogC2WsHjmDveEMvsWXEsol8zsrS5locdOt161BWE44HHoKy48jA4SrIOpK9nsAVjqsdjcWGM0t/3xK1kbBuMWNCF8NDj2J7LDg2UwAtM1jgbbSYeOTFTv2Kjc2uJvT9NT3ykNJaUgi7MIjInC/8bwzAEd+WF6/1gaJZfJ7s9OrdMXDnDs16xmhmklgxOpRhxfjkvTf7lYRjGq40EzNlyity0geX+/dbmEDSnw3sHF7rNGWZCSeYV/mQjqsQkK0J1nCev8w9tGhHUarq1FHAP0rrOFWkzEt4sRZkAUbLqYfMN0Oi0ZpIa8hsUg3Kfh5djetwBXuRODEnA/X4yRQUTHarGqQiloeywvjdHLbXcYHBpu8xsPQr/xsLFB4wSHW0R9E+oYmW1VuoLcSP/ZqEvkcluUCK43YzJw3ks9SRrWj4pWTQ//g1/KkaLrcLRfZKKAww5vpw/HJ6oGNesu6Odt0ksx5FwQAemvVouePV6RFR3+vJXyrmMLJ5eylw3PjrCl4hwhJ0KOpaFHEnEgegAh57++tyBg3Iyi/H35msgVzOA74Lf+ULxHN4UUtGfoQjN/Ltqj89BPZQzVMof1Od9JvNnzBUQ=
