#
#  To be included when running `ansible_playbook -i environments/local openwhisk`
#  by adding a `-e ${RUNTIME_NODEJS_HOME}\ansible\nodejs_runtimes.yml` parameter
#
runtimes_manifest:
  defaultImagePrefix: "openwhisk"
  defaultImageTag: "latest"
  runtimes:
    nodejs:
    - kind: "nodejs:6"
      default: true
      image:
        name: "nodejs6action"
      deprecated: false
    - kind: "nodejs:8"
      default: false
      image:
        name: "action-nodejs-v8"
      deprecated: false
  blackboxes:
    - name: "dockerskeleton"
